### PR TITLE
Bump wlroots dependency to 0.15.0

### PR DESCRIPTION
**Pull request by inclement**

### CODE REVIEW

**Comment by inclement** [comment]
This needs fixing up for the released version of wlroots 0.15.

**Comment by inclement** [comment]
This seems to be working fine/correctly, but now bemenu-run never maps itself. Investigating this before merging.

**Comment by flaviozavan** [comment]
With 0.15.1 already out and 0.16 in the near future, it may be a good time to look into merging this.

I investigated the layer shell issue and wrote a fix;
I also noticed fullscreen was broken, and fixed it as well;
And finally, I also updated the wlroots version in the wraps file.

I pushed a [working branch here](https://github.com/flaviozavan/vivarium/tree/wlr-0.15) (using it right now). There's more info about each of the issues in the commit messages

**Comment by inclement** [comment]
That looks great @flaviozavan, I'd be happy to merge with your additional fixes - do you want to make an MR? I'll test it a bit first but if you've also been testing I don't anticipate any issues.

**Comment by flaviozavan** [comment]
It's fine if you just want to include my changes here, I could also create the PR. However, just last time I noticed mouse focusing issues on GIMP. If you open gimp and have it be the only window in the workpace, then click New Image, you get this secondary window that you can interact with via the keyboard, but all mouse clicks end up in the main window behind it. Having more windows sometimes fixes this. Naturally I am trying to debug this, though It's been extra tricky as all cursor events seems to be being sent to the right view/surface.

**Comment by flaviozavan** [comment]
I ended up figuring it out just a couple of minutes after replying. It was related to this https://github.com/swaywm/wlroots/pull/2915. The fix is in my branch. Feel free to include everything here and merge

**Pull request merged**
