### PR TITLE
Create Wiki (See comment), leave hyperlink to wiki in README

### PR DESCRIPTION
**Pull request by proudmuslim-dev**
Hi!

I've created a wiki for the project at [https://github.com/proudmuslim-dev/vivarium/wiki](https://github.com/proudmuslim-dev/vivarium/wiki), and some of your existing stuff (the configuration and FAQ sections) over to it. The issue is that GitHub doesn't allow you to PR wikis, so you're going to have to merge it manually. Since I've never dealt with this before, I've found a [gist](https://gist.github.com/larrybotha/10650410) explaining how to merge them manually.

### CODE REVIEW

**Comment by inclement** [comment]
Thanks - I have mixed feelings about committing to the Github wiki, especially for "official" documentation, as wikis tend to have the problem that since they're well removed from the code they're easy to forget to update when things change. I think they work much better for higher level things like general high-level tips on configuration and tooling, which aren't something you'd necessarily document so much in the code, and which are more amenable to user contribution.

My immediate preference is to instead focus on generating documentation from the repository contents (i.e. with doxygen for the code and some actual man page stuff), leaving the README as the most official source for now. This also has the advantage of being less tied to the Github ecosystem. I'm happy to have wiki pages that people can contribute to, and even happier if people actually want to do so, just not as the primary documentation source.

**Comment by proudmuslim-dev** [comment]
I see your point here, and it makes sense. I can easily see the wiki going without updates, although I did come across some hacky workarounds to tie it into the repo. I can understand wanting to get away from the github ecosystem, but in my opinion I feel as though it would be better to at least have a small wiki starting out, at least until another means of hosting the documentation is decided upon. Even if this doesn't see any use as a primary source of documentation, I still believe that it could still see use as a place for unofficial tips and tricks on setting up the compositor.

Of course, this is still a young project, and there isn't a community around it yet. There's still plenty of time to explore different means of providing good documentation and user experience - the wiki is just the tip of the iceberg, after all. There are still a lot of decisions you'll probably have to make regarding contributing guidelines and a center for discussion/help, so I can completely understand this PR getting closed or put on hold.

**Comment by inclement** [comment]
I'm happy to have the wiki enabled - actually I'm not sure how github works, can you already edit it or do I need to do something to enable edits from anyone?

I'll close this for now, but will definitely bear it in mind when looking at how to handle documentation.

**Comment by inclement** [comment]
I'll also leave the current README content in place for now.

**Comment by proudmuslim-dev** [comment]
> I'm happy to have the wiki enabled - actually I'm not sure how github works, can you already edit it or do I need to do something to enable edits from anyone?
> 
> I'll close this for now, but will definitely bear it in mind when looking at how to handle documentation.

Hi, I hadn't seen your reply initially, sorry about that. I believe there isn't anything you in particular that you have to do beyond making the first page and enabling it, however I've never set up one for a use case like this, so I could be wrong there. 

It's great to hear that you'll consider it, as the wiki page on a repo is often one of the first places I go right after the README, and I feel like it's a great way to centralize the user documentation and bug reporting.

**Pull request closed without merging**
